import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
const inter = Poppins({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: "Food Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
